#!/bin/bash
# merge-beta.sh — Merge functions-beta codebase into functions/ for single-emulator dev
set -e
cd /home/super/Work/scifsys

echo "=== Merging functions-beta into functions/ for single-emulator dev ==="
echo ""

# Backup current functions/index.js if not already backed up
if [ ! -f functions/index.js.orig-backup ]; then
    cp functions/index.js functions/index.js.orig-backup
    echo "Backed up functions/index.js → functions/index.js.orig-backup"
fi

# Merge beta functions into the functions/ entry point
cat > functions/index.js << 'ENDOFFILE'
/**
 * SCIFsys Functions — Unified Entry Point (Stable + Beta)
 *
 * For local emulator development, both stable and beta codebases
 * are loaded from a single entry point so they're available on
 * the same emulator instance.
 *
 * Stable functions: exported as-is
 * Beta functions: prefixed with "beta_" to avoid naming conflicts
 *
 * DO NOT edit this file for production deployments.
 * For production, restore from functions/index.js.orig-backup.
 */

// === Stable functions (primary codebase) ===
const stable = require('./src/main');

Object.keys(stable).forEach(key => {
  exports[key] = stable[key];
});

if (stable.__test__) exports.__test__ = stable.__test__;
if (stable._test) exports._test = stable._test;

// === Beta functions (prefixed for local dev) ===
const betaSrcPath = '../functions-beta/src/main';
const betaSyncPath = '../functions-beta/src/beta-sync';

let betaMain, betaSync;
try {
  betaMain = require(betaSrcPath);
  console.log('[functions] Loaded beta codebase: main.js');
} catch (e) {
  console.warn('[functions] Warning: could not load functions-beta/src/main:', e.message);
}

try {
  betaSync = require(betaSyncPath);
  console.log('[functions] Loaded beta codebase: beta-sync.js');
} catch (e) {
  console.warn('[functions] Warning: could not load functions-beta/src/beta-sync:', e.message);
}

if (betaMain) {
  Object.keys(betaMain).forEach(key => {
    exports['beta_' + key] = betaMain[key];
  });
  console.log('[functions] Beta exports prefixed: ' + Object.keys(betaMain).join(', '));
}

if (betaSync) {
  Object.keys(betaSync).forEach(key => {
    exports['beta_' + key] = betaSync[key];
  });
  console.log('[functions] Beta sync exports prefixed: ' + Object.keys(betaSync).join(', '));
}

console.log('[functions] Total exports: ' + Object.keys(exports).length);
ENDOFFILE

echo ""
echo "=== Verifying merged index.js loads ==="
PATH="/home/super/.local/share/mise/installs/node/22.23.2/bin:$PATH" node -e "
try {
  const m = require('./functions/index.js');
  const keys = Object.keys(m);
  console.log('Total exports: ' + keys.length);
  console.log('Stable exports: ' + keys.filter(k => !k.startsWith('beta_')).length);
  console.log('Beta exports: ' + keys.filter(k => k.startsWith('beta_')).length);
  console.log('');
  console.log('Beta prefixed functions:');
  keys.filter(k => k.startsWith('beta_')).forEach(k => console.log('  - ' + k));
  console.log('');
  console.log('Sample stable functions:');
  keys.filter(k => !k.startsWith('beta_')).slice(0, 10).forEach(k => console.log('  - ' + k));
} catch (e) {
  console.error('FAILED to load:', e.message);
  process.exit(1);
}
" 2>&1